# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'captcha.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os

try:
    os.chdir(sys._MEIPASS)
except:
    pass

class Ui_Captcha_Form(object):
    def setupUi(self, Captcha_Form):
        Captcha_Form.setObjectName("Captcha_Form")
        Captcha_Form.resize(400, 300)
        Captcha_Form.setMinimumSize(QtCore.QSize(400, 300))
        Captcha_Form.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Data/Images/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Captcha_Form.setWindowIcon(icon)
        self.Resp_label = QtWidgets.QLabel(Captcha_Form)
        self.Resp_label.setGeometry(QtCore.QRect(90, -10, 211, 71))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Resp_label.setFont(font)
        self.Resp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Resp_label.setObjectName("Resp_label")
        self.Captcha_label = QtWidgets.QLabel(Captcha_Form)
        self.Captcha_label.setGeometry(QtCore.QRect(40, 50, 311, 111))
        self.Captcha_label.setText("")
        self.movie=QtGui.QMovie("Data/Images/loading.gif")
        self.Captcha_label.setMovie(self.movie)
        self.movie.start()
        self.Captcha_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Captcha_label.setObjectName("Captcha_label")
        self.Enter_btn = QtWidgets.QPushButton(Captcha_Form)
        self.Enter_btn.setEnabled(False)
        self.Enter_btn.setGeometry(QtCore.QRect(130, 220, 131, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Enter_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Enter_btn.setFont(font)
        self.Enter_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Enter_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Data/Images/Enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Enter_btn.setIcon(icon1)
        self.Enter_btn.setIconSize(QtCore.QSize(50, 50))
        self.Enter_btn.setObjectName("Enter_btn")
        self.Captcha_Field = QtWidgets.QLineEdit(Captcha_Form)
        self.Captcha_Field.setEnabled(False)
        self.Captcha_Field.setGeometry(QtCore.QRect(102, 170, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(17)
        self.Captcha_Field.setFont(font)
        self.Captcha_Field.setText("")
        self.Captcha_Field.setAlignment(QtCore.Qt.AlignCenter)
        self.Captcha_Field.setObjectName("Captcha_Field")

        self.retranslateUi(Captcha_Form)
        QtCore.QMetaObject.connectSlotsByName(Captcha_Form)

    def retranslateUi(self, Captcha_Form):
        _translate = QtCore.QCoreApplication.translate
        Captcha_Form.setWindowTitle(_translate("Captcha_Form", "Captcha"))
        self.Resp_label.setText(_translate("Captcha_Form", "عبارت زیر را وارد کنید:"))
        self.Enter_btn.setToolTip(_translate("Captcha_Form", "ورود به حساب کاربری"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Captcha_Form = QtWidgets.QWidget()
    ui = Ui_Captcha_Form()
    ui.setupUi(Captcha_Form)
    Captcha_Form.show()
    sys.exit(app.exec_())
